services:

  web:
    container_name: until_web
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - /var/www/until/env.prod
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/www/until/app:/var/www/until/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
